In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../data/pivoted_scaled_and_noise_removal.csv", index_col=0)

In [3]:
df.head()

,200.0,200.68336,201.36674,202.05011,202.73349,203.41685,204.10023,204.7836,205.46696,206.15034,...,1994.5331,1995.2164,1995.8998,1996.5831,1997.2665,1997.9498,1998.6333,1999.3167,2000.0,Status
SpecID,,,,,,,,,,,,,,,,,,,,,
201210-1-00,1.000000,0.982870,0.966481,0.950833,0.935925,0.927346,0.902431,0.889797,0.880243,0.864841,...,0.070690,0.082414,0.090970,0.092890,0.083230,0.082239,0.082605,0.084328,0.087409,Normal
201210-1-01,1.000000,0.980550,0.964007,0.950373,0.939647,0.930871,0.928574,0.925606,0.914910,0.900030,...,0.113337,0.117351,0.131463,0.146428,0.158236,0.161601,0.160516,0.154980,0.144994,Normal
201210-1-02,0.502527,0.491051,0.479540,0.467993,0.456410,0.450161,0.431959,0.424441,0.417415,0.408823,...,0.144569,0.141991,0.139207,0.144627,0.149526,0.150847,0.150600,0.148786,0.145404,Normal
201210-1-03,0.492251,0.418315,0.375666,0.364304,0.384230,0.461173,0.570848,0.577491,0.675831,0.807648,...,0.005644,0.007747,0.008992,0.010157,0.011991,0.011822,0.010642,0.008451,0.005248,Normal
201210-1-04,1.000000,0.994372,0.989487,0.985346,0.981948,0.976845,0.970762,0.977536,0.981513,0.963198,...,0.019359,0.028442,0.041845,0.058730,0.063852,0.070008,0.074530,0.077417,0.078669,Normal

Use the Gausian Kernal Function to Map the Euclidian Distance between all the samples between 0 and 1.

Calculate the euclidean distance between each pair of samples.

In [4]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Drop the 'Status' column as it is not numeric
X = df.drop(columns=['Status'])

# Calculate pairwise Euclidean distances
distances = pdist(X.values, metric='euclidean')

# Convert the condensed distances to a square matrix form
distance_matrix = squareform(distances)

Complete the Gaussian Kernel.

Different Sigmas should be tested.

In [5]:
import numpy as np

def gaussian_kernel(distances, sigma):
    return np.exp(-distances**2 / (2 * sigma**2))

# Sigma is the bandwidth parameter
sigma = 2.0  # Adjust sigma as needed
kernel_matrix = gaussian_kernel(distance_matrix, sigma)

# Convert the kernel matrix to a DataFrame
kernel_df = pd.DataFrame(kernel_matrix, index=df.index, columns=df.index)

In [6]:
kernel_df

SpecID,201210-1-00,201210-1-01,201210-1-02,201210-1-03,201210-1-04,201210-1-05,201210-1-06,201210-1-07,201210-1-09,201210-1-10,...,210526-3-40,210526-3-41,210526-3-42,210526-3-43,210526-3-44,210526-3-45,210526-3-46,210526-3-47,210526-3-48,210526-3-49
SpecID,,,,,,,,,,,,,,,,,,,,,
201210-1-00,1.000000,0.498621,0.001474,0.033503,0.139113,0.147200,0.116846,0.087971,0.074254,0.107226,...,0.023542,0.016914,0.011799,0.019152,0.019031,0.027628,0.024572,0.033234,0.023375,0.033534
201210-1-01,0.498621,1.000000,0.003655,0.031270,0.135313,0.145222,0.166514,0.103411,0.099525,0.110719,...,0.015006,0.011432,0.008478,0.011922,0.011305,0.019022,0.015977,0.022697,0.015352,0.021558
201210-1-02,0.001474,0.003655,1.000000,0.034599,0.000063,0.000158,0.000556,0.002848,0.002976,0.001750,...,0.000057,0.000028,0.000033,0.000033,0.000032,0.000095,0.000061,0.000315,0.000047,0.000144
201210-1-03,0.033503,0.031270,0.034599,1.000000,0.002231,0.003921,0.022159,0.105841,0.069924,0.037440,...,0.001582,0.000840,0.000740,0.001059,0.001015,0.002444,0.001509,0.004226,0.001383,0.002989
201210-1-04,0.139113,0.135313,0.000063,0.002231,1.000000,0.407746,0.063997,0.015887,0.011784,0.027026,...,0.026700,0.023048,0.014931,0.023701,0.023082,0.027218,0.028355,0.025232,0.025729,0.027837
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210526-3-45,0.027628,0.019022,0.000095,0.002444,0.027218,0.030038,0.017157,0.005321,0.003133,0.009699,...,0.566961,0.510720,0.438520,0.535863,0.542634,1.000000,0.545757,0.485496,0.523684,0.469168
210526-3-46,0.024572,0.015977,0.000061,0.001509,0.028355,0.031541,0.014614,0.004096,0.002500,0.008301,...,0.559920,0.548778,0.411034,0.569511,0.521280,0.545757,1.000000,0.460726,0.521503,0.482807
210526-3-47,0.033234,0.022697,0.000315,0.004226,0.025232,0.029996,0.016999,0.006487,0.003978,0.010836,...,0.448601,0.420765,0.333019,0.430109,0.405293,0.485496,0.460726,1.000000,0.429772,0.470131
210526-3-48,0.023375,0.015352,0.000047,0.001383,0.025729,0.024952,0.013394,0.003441,0.002066,0.007276,...,0.546158,0.510684,0.369582,0.542970,0.524964,0.523684,0.521503,0.429772,1.000000,0.455532
210526-3-49,0.033534,0.021558,0.000144,0.002989,0.027837,0.032010,0.017971,0.006528,0.003910,0.011465,...,0.508259,0.424111,0.330363,0.471578,0.450585,0.469168,0.482807,0.470131,0.455532,1.000000

Create the graph structure.

Create the node information.

In [7]:
df.index

Index(['201210-1-00', '201210-1-01', '201210-1-02', '201210-1-03',
       '201210-1-04', '201210-1-05', '201210-1-06', '201210-1-07',
       '201210-1-09', '201210-1-10',
       ...
       '210526-3-40', '210526-3-41', '210526-3-42', '210526-3-43',
       '210526-3-44', '210526-3-45', '210526-3-46', '210526-3-47',
       '210526-3-48', '210526-3-49'],
      dtype='object', name='SpecID', length=3045)

In [8]:
nodes_df = df['Status'].to_frame()
nodes_df.head()

             Status
SpecID
201210-1-00  Normal
201210-1-01  Normal
201210-1-02  Normal
201210-1-03  Normal
201210-1-04  Normal

Use the Neo4j Naming Scheme.

Create the nodes CSV.

In [9]:
nodes_df = nodes_df.rename_axis("SpecID:ID")
nodes_df = nodes_df.rename(columns={"Status": ":LABEL"})

In [10]:
nodes_df

                    :LABEL
SpecID:ID
201210-1-00         Normal
201210-1-01         Normal
201210-1-02         Normal
201210-1-03         Normal
201210-1-04         Normal
...                    ...
210526-3-45  Hyperglycemia
210526-3-46  Hyperglycemia
210526-3-47  Hyperglycemia
210526-3-48  Hyperglycemia
210526-3-49  Hyperglycemia

[3045 rows x 1 columns]

In [11]:
nodes_df.to_csv("../../data/gaussian_kernel/nodes.csv")

Create the relationships CSV.

In [12]:
kernel_df.head()

SpecID,201210-1-00,201210-1-01,201210-1-02,201210-1-03,201210-1-04,201210-1-05,201210-1-06,201210-1-07,201210-1-09,201210-1-10,...,210526-3-40,210526-3-41,210526-3-42,210526-3-43,210526-3-44,210526-3-45,210526-3-46,210526-3-47,210526-3-48,210526-3-49
SpecID,,,,,,,,,,,,,,,,,,,,,
201210-1-00,1.000000,0.498621,0.001474,0.033503,0.139113,0.147200,0.116846,0.087971,0.074254,0.107226,...,0.023542,0.016914,0.011799,0.019152,0.019031,0.027628,0.024572,0.033234,0.023375,0.033534
201210-1-01,0.498621,1.000000,0.003655,0.031270,0.135313,0.145222,0.166514,0.103411,0.099525,0.110719,...,0.015006,0.011432,0.008478,0.011922,0.011305,0.019022,0.015977,0.022697,0.015352,0.021558
201210-1-02,0.001474,0.003655,1.000000,0.034599,0.000063,0.000158,0.000556,0.002848,0.002976,0.001750,...,0.000057,0.000028,0.000033,0.000033,0.000032,0.000095,0.000061,0.000315,0.000047,0.000144
201210-1-03,0.033503,0.031270,0.034599,1.000000,0.002231,0.003921,0.022159,0.105841,0.069924,0.037440,...,0.001582,0.000840,0.000740,0.001059,0.001015,0.002444,0.001509,0.004226,0.001383,0.002989
201210-1-04,0.139113,0.135313,0.000063,0.002231,1.000000,0.407746,0.063997,0.015887,0.011784,0.027026,...,0.026700,0.023048,0.014931,0.023701,0.023082,0.027218,0.028355,0.025232,0.025729,0.027837

In [36]:
relationship_df = kernel_df.reset_index()
relationship_df = relationship_df.melt(id_vars='SpecID', var_name=':END_ID', value_name='Weight:float')
relationship_df = relationship_df.rename(columns={'SpecID': ':START_ID'})
relationship_df[':TYPE'] = 'LINK'

In [37]:
relationship_df

           :START_ID      :END_ID  Weight:float :TYPE
0        201210-1-00  201210-1-00      1.000000  LINK
1        201210-1-01  201210-1-00      0.498621  LINK
2        201210-1-02  201210-1-00      0.001474  LINK
3        201210-1-03  201210-1-00      0.033503  LINK
4        201210-1-04  201210-1-00      0.139113  LINK
...              ...          ...           ...   ...
9272020  210526-3-45  210526-3-49      0.469168  LINK
9272021  210526-3-46  210526-3-49      0.482807  LINK
9272022  210526-3-47  210526-3-49      0.470131  LINK
9272023  210526-3-48  210526-3-49      0.455532  LINK
9272024  210526-3-49  210526-3-49      1.000000  LINK

[9272025 rows x 4 columns]

Drop all the relationships a node has with itself, as well as the repeated two way relationship.

In [38]:
relationship_df = relationship_df[relationship_df[":START_ID"] != relationship_df[":END_ID"]]
relationship_df = relationship_df[relationship_df[":START_ID"] < relationship_df[":END_ID"]]

In [39]:
relationship_df

           :START_ID      :END_ID  Weight:float :TYPE
3045     201210-1-00  201210-1-01      0.498621  LINK
6090     201210-1-00  201210-1-02      0.001474  LINK
6091     201210-1-01  201210-1-02      0.003655  LINK
9135     201210-1-00  201210-1-03      0.033503  LINK
9136     201210-1-01  201210-1-03      0.031270  LINK
...              ...          ...           ...   ...
9272019  210526-3-44  210526-3-49      0.450585  LINK
9272020  210526-3-45  210526-3-49      0.469168  LINK
9272021  210526-3-46  210526-3-49      0.482807  LINK
9272022  210526-3-47  210526-3-49      0.470131  LINK
9272023  210526-3-48  210526-3-49      0.455532  LINK

[4634490 rows x 4 columns]

In [40]:
relationship_df.to_csv("../../data/gaussian_kernel/relationships.csv",index=False)