In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("../../data/pivoted_scaled_and_noise_removal.csv", index_col=0)

In [14]:
df.head()

,200.0,200.68336,201.36674,202.05011,202.73349,203.41685,204.10023,204.7836,205.46696,206.15034,...,1994.5331,1995.2164,1995.8998,1996.5831,1997.2665,1997.9498,1998.6333,1999.3167,2000.0,Status
SpecID,,,,,,,,,,,,,,,,,,,,,
201210-1-00,1.000000,0.982870,0.966481,0.950833,0.935925,0.927346,0.902431,0.889797,0.880243,0.864841,...,0.070690,0.082414,0.090970,0.092890,0.083230,0.082239,0.082605,0.084328,0.087409,Normal
201210-1-01,1.000000,0.980550,0.964007,0.950373,0.939647,0.930871,0.928574,0.925606,0.914910,0.900030,...,0.113337,0.117351,0.131463,0.146428,0.158236,0.161601,0.160516,0.154980,0.144994,Normal
201210-1-02,0.502527,0.491051,0.479540,0.467993,0.456410,0.450161,0.431959,0.424441,0.417415,0.408823,...,0.144569,0.141991,0.139207,0.144627,0.149526,0.150847,0.150600,0.148786,0.145404,Normal
201210-1-03,0.492251,0.418315,0.375666,0.364304,0.384230,0.461173,0.570848,0.577491,0.675831,0.807648,...,0.005644,0.007747,0.008992,0.010157,0.011991,0.011822,0.010642,0.008451,0.005248,Normal
201210-1-04,1.000000,0.994372,0.989487,0.985346,0.981948,0.976845,0.970762,0.977536,0.981513,0.963198,...,0.019359,0.028442,0.041845,0.058730,0.063852,0.070008,0.074530,0.077417,0.078669,Normal

Use the Gausian Kernal Function to Map the Euclidian Distance between all the samples between 0 and 1.

Calculate the euclidean distance between each pair of samples.

In [15]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Drop the 'Status' column as it is not numeric
X = df.drop(columns=['Status'])

# Calculate pairwise Euclidean distances
distances = pdist(X.values, metric='euclidean')

# Convert the condensed distances to a square matrix form
distance_matrix = squareform(distances)

Complete the Gaussian Kernel.

Different Sigmas should be tested.

In [100]:
import numpy as np

def gaussian_kernel(distances, sigma):
    return np.exp(-distances**2 / (2 * sigma**2))

# Sigma is the bandwidth parameter
sigma = 5 # Adjust sigma as needed
kernel_matrix = gaussian_kernel(distance_matrix, sigma)

# Convert the kernel matrix to a DataFrame
kernel_df = pd.DataFrame(kernel_matrix, index=df.index, columns=df.index)

In [101]:
kernel_df

SpecID,201210-1-00,201210-1-01,201210-1-02,201210-1-03,201210-1-04,201210-1-05,201210-1-06,201210-1-07,201210-1-09,201210-1-10,...,210526-3-40,210526-3-41,210526-3-42,210526-3-43,210526-3-44,210526-3-45,210526-3-46,210526-3-47,210526-3-48,210526-3-49
SpecID,,,,,,,,,,,,,,,,,,,,,
201210-1-00,1.000000,0.894630,0.352346,0.580781,0.729355,0.735979,0.709280,0.677789,0.659652,0.699597,...,0.548901,0.520620,0.491469,0.531072,0.530533,0.563141,0.552675,0.580035,0.548277,0.580868
201210-1-01,0.894630,1.000000,0.407430,0.574409,0.726130,0.734387,0.750640,0.695554,0.691304,0.703195,...,0.510744,0.488992,0.466147,0.492284,0.488119,0.530495,0.515895,0.545703,0.512607,0.541225
201210-1-02,0.352346,0.407430,1.000000,0.583782,0.212543,0.246364,0.301411,0.391488,0.394266,0.362152,...,0.209162,0.187038,0.191487,0.192305,0.190531,0.227350,0.211646,0.275215,0.202931,0.242785
201210-1-03,0.580781,0.574409,0.583782,1.000000,0.376487,0.412051,0.543609,0.698144,0.653341,0.591198,...,0.356342,0.322006,0.315554,0.334166,0.331941,0.382020,0.353671,0.417015,0.348770,0.394539
201210-1-04,0.729355,0.726130,0.212543,0.376487,1.000000,0.866288,0.644149,0.515426,0.491367,0.561159,...,0.560071,0.547044,0.510333,0.549495,0.547174,0.561795,0.565484,0.555025,0.556761,0.563820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210526-3-45,0.563141,0.530495,0.227350,0.382020,0.561795,0.570726,0.521807,0.432669,0.397516,0.476296,...,0.913205,0.898068,0.876432,0.905000,0.906820,1.000000,0.907653,0.890820,0.901677,0.885957
210526-3-46,0.552675,0.515895,0.211646,0.353671,0.565484,0.575201,0.508584,0.414935,0.383425,0.464585,...,0.911381,0.908455,0.867402,0.913861,0.901014,0.907653,1.000000,0.883387,0.901075,0.890028
210526-3-47,0.580035,0.545703,0.275215,0.417015,0.555025,0.570597,0.521037,0.446609,0.412989,0.484819,...,0.879625,0.870656,0.838678,0.873721,0.865452,0.890820,0.883387,1.000000,0.873611,0.886248
210526-3-48,0.548277,0.512607,0.202931,0.348770,0.556761,0.554034,0.501542,0.403521,0.371897,0.454886,...,0.907760,0.898058,0.852773,0.906910,0.902030,0.901677,0.901075,0.873611,1.000000,0.881786
210526-3-49,0.580868,0.541225,0.242785,0.394539,0.563820,0.576561,0.525691,0.447057,0.411857,0.489212,...,0.897374,0.871760,0.837604,0.886683,0.880246,0.885957,0.890028,0.886248,0.881786,1.000000

Create the graph structure.

Create the node information.

In [102]:
df.index

Index(['201210-1-00', '201210-1-01', '201210-1-02', '201210-1-03',
       '201210-1-04', '201210-1-05', '201210-1-06', '201210-1-07',
       '201210-1-09', '201210-1-10',
       ...
       '210526-3-40', '210526-3-41', '210526-3-42', '210526-3-43',
       '210526-3-44', '210526-3-45', '210526-3-46', '210526-3-47',
       '210526-3-48', '210526-3-49'],
      dtype='object', name='SpecID', length=3045)

In [103]:
nodes_df = df['Status'].to_frame()
nodes_df.head()

             Status
SpecID
201210-1-00  Normal
201210-1-01  Normal
201210-1-02  Normal
201210-1-03  Normal
201210-1-04  Normal

Use the Neo4j Naming Scheme.

Create the nodes CSV.

In [104]:
nodes_df = nodes_df.rename_axis("SpecID:ID")
nodes_df = nodes_df.rename(columns={"Status": ":LABEL"})

In [105]:
nodes_df

                    :LABEL
SpecID:ID
201210-1-00         Normal
201210-1-01         Normal
201210-1-02         Normal
201210-1-03         Normal
201210-1-04         Normal
...                    ...
210526-3-45  Hyperglycemia
210526-3-46  Hyperglycemia
210526-3-47  Hyperglycemia
210526-3-48  Hyperglycemia
210526-3-49  Hyperglycemia

[3045 rows x 1 columns]

In [106]:
#nodes_df.to_csv("../../data/gaussian_kernel/nodes.csv")
nodes_df.to_csv("../../data/current_working_graph/nodes.csv")

Create the relationships CSV.

In [107]:
kernel_df.head()

SpecID,201210-1-00,201210-1-01,201210-1-02,201210-1-03,201210-1-04,201210-1-05,201210-1-06,201210-1-07,201210-1-09,201210-1-10,...,210526-3-40,210526-3-41,210526-3-42,210526-3-43,210526-3-44,210526-3-45,210526-3-46,210526-3-47,210526-3-48,210526-3-49
SpecID,,,,,,,,,,,,,,,,,,,,,
201210-1-00,1.000000,0.894630,0.352346,0.580781,0.729355,0.735979,0.709280,0.677789,0.659652,0.699597,...,0.548901,0.520620,0.491469,0.531072,0.530533,0.563141,0.552675,0.580035,0.548277,0.580868
201210-1-01,0.894630,1.000000,0.407430,0.574409,0.726130,0.734387,0.750640,0.695554,0.691304,0.703195,...,0.510744,0.488992,0.466147,0.492284,0.488119,0.530495,0.515895,0.545703,0.512607,0.541225
201210-1-02,0.352346,0.407430,1.000000,0.583782,0.212543,0.246364,0.301411,0.391488,0.394266,0.362152,...,0.209162,0.187038,0.191487,0.192305,0.190531,0.227350,0.211646,0.275215,0.202931,0.242785
201210-1-03,0.580781,0.574409,0.583782,1.000000,0.376487,0.412051,0.543609,0.698144,0.653341,0.591198,...,0.356342,0.322006,0.315554,0.334166,0.331941,0.382020,0.353671,0.417015,0.348770,0.394539
201210-1-04,0.729355,0.726130,0.212543,0.376487,1.000000,0.866288,0.644149,0.515426,0.491367,0.561159,...,0.560071,0.547044,0.510333,0.549495,0.547174,0.561795,0.565484,0.555025,0.556761,0.563820

In [108]:
relationship_df = kernel_df.reset_index()
relationship_df = relationship_df.melt(id_vars='SpecID', var_name=':END_ID', value_name='Weight:float')
relationship_df = relationship_df.rename(columns={'SpecID': ':START_ID'})
relationship_df[':TYPE'] = 'LINK'

In [109]:
relationship_df

           :START_ID      :END_ID  Weight:float :TYPE
0        201210-1-00  201210-1-00      1.000000  LINK
1        201210-1-01  201210-1-00      0.894630  LINK
2        201210-1-02  201210-1-00      0.352346  LINK
3        201210-1-03  201210-1-00      0.580781  LINK
4        201210-1-04  201210-1-00      0.729355  LINK
...              ...          ...           ...   ...
9272020  210526-3-45  210526-3-49      0.885957  LINK
9272021  210526-3-46  210526-3-49      0.890028  LINK
9272022  210526-3-47  210526-3-49      0.886248  LINK
9272023  210526-3-48  210526-3-49      0.881786  LINK
9272024  210526-3-49  210526-3-49      1.000000  LINK

[9272025 rows x 4 columns]

Drop all the relationships a node has with itself, as well as the repeated two way relationship.

In [110]:
relationship_df = relationship_df[relationship_df[":START_ID"] != relationship_df[":END_ID"]]
relationship_df = relationship_df[relationship_df[":START_ID"] < relationship_df[":END_ID"]]

In [111]:
relationship_df

           :START_ID      :END_ID  Weight:float :TYPE
3045     201210-1-00  201210-1-01      0.894630  LINK
6090     201210-1-00  201210-1-02      0.352346  LINK
6091     201210-1-01  201210-1-02      0.407430  LINK
9135     201210-1-00  201210-1-03      0.580781  LINK
9136     201210-1-01  201210-1-03      0.574409  LINK
...              ...          ...           ...   ...
9272019  210526-3-44  210526-3-49      0.880246  LINK
9272020  210526-3-45  210526-3-49      0.885957  LINK
9272021  210526-3-46  210526-3-49      0.890028  LINK
9272022  210526-3-47  210526-3-49      0.886248  LINK
9272023  210526-3-48  210526-3-49      0.881786  LINK

[4634490 rows x 4 columns]

In [112]:
#relationship_df.to_csv("../../data/gaussian_kernel/relationships.csv",index=False)

In [113]:
nodes_df.to_csv("../../data/gaussian_kernel/nodes.csv")
relationship_df.to_csv("../../data/current_working_graph/relationships.csv")